AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'spec/{rails_helper.rb,spec_helper.rb}'
    - 'config.ru'
    - 'Rakefile'

Style/FrozenStringLiteralComment:
  Enabled: false