version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/blog
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  dbdata:
