version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/blog
    ports:
      - "3000:3000"
    depends_on:
      - db
  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
volumes:
  dbdata:
