name: "CI/CD"

on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  Test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: blog_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - "5432:5432"

    steps:
      - uses: actions/checkout@v3
   
      - name: Install Ruby and dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - run: bundle install

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/blog_test
          RAILS_ENV: test
          PG_USER: postgres
        run: |
          bin/rails db:test:prepare
          bundle exec rspec

      - name: Lint
        run: bundle exec rubocop

      - name: Build image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          docker build -t momconnor38/rails-blog-k8s:latest -t momconnor38/rails-blog-k8s:${{ env.SHA }} .

      - name: Push image
        run: |
          docker push momconnor38/rails-blog-k8s:latest
          docker push momconnor38/rails-blog-k8s:${{ env.SHA }}

      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
  
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: '${{ secrets.GKE_PROJECT_ID }}' 
  
      - name: Auth
        run: |
          gcloud --quiet auth configure-docker
  
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: '${{ secrets.GKE_CLUSTER_NAME }}'
          location: europe-west1

      - name: Apply
        run: |
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=momconnor38/rails-blog-k8s:${{ env.SHA }}
