name: "Deploy"

on:
  workflow_dispatch:

env:
  SHA: $(git rev-parse HEAD)
  
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set Service Key
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - name: Set Project
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: '${{ secrets.GKE_PROJECT_ID }}' 

    - name: Auth
      run: |
        gcloud --quiet auth configure-docker

    - name: Get Credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
        location: europe-west1

    - name: Apply
      run: |
        kubectl apply -f k8s
        kubectl set image deployments/server-deployment server=momconnor38/testgcd:${{ env.SHA }}
